const types = {
  WATCH_ADD_POST: "WATCH_ADD_POST",
  ADD_POST: "ADD_POST",
  WATCH_FETCH_POSTS: "WATCH_FETCH_POSTS",
  FETCH_POSTS: "FETCH_POSTS",
  WATCH_UPDATE_POST: "WATCH_UPDATE_POST",
  UPDATE_POST: "UPDATE_POST",
  WATCH_DELETE_POST: "WATCH_DELETE_POST",
  DELETE_POST: "DELETE_POST"
};

export default types;
