const types = {
  WATCH_LOGIN: "WATCH_LOGIN",
  WATCH_LOGOUT: "WATCH_LOGOUT",
  LOGIN: "LOGIN",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  WATCH_AUTH: "WATCH_AUTH",
  WATCH_GET_USER: "WATCH_GET_USER",
  GET_USER: "GET_USER"
};

export default types;
